# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'capstone' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for capstone
	pod 'Parse'
  pod 'AFNetworking'
  pod 'MKDropdownMenu'


  target 'capstoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'capstoneUITests' do
    # Pods for testing
  end

end
